### ISSUE TITLE
Breaking LostPassword / extended Email classes?

### ISSUE THREAD

**Issue by nzphoenix** [unclecheese/silverstripe-permamail#2]
I've been implementing permamail for use in an application, but found it had the side-affect of affecting the lostpassword email (Member_ForgotPasswordEmail). It appears that when this class is created it extends Email, setting the subject and template in the process.

However, the Permamail injector forces the permamail class, meaning the Member_ForgotPasswordEmail::create doesn't actually set the $ss_template or subject - resulting in blank emails being sent (in framework/security/Member.php line 1690). Overwriting the injector in mysite config to the class 'Email' also means we're still not allowing it to use the Member_ForgotPasswordEmail extended class. 

Resolved it by removing the injector completly in mysite/config, but feel like there could be a better solution I haven't spotted?

**Comment by unclecheese** [comment]
This is fixed in the `1.0.0` tagged release.
